version: '3.5'

services:
  webapp:
    build:
      context: .
      dockerfile: docker/config/webapp/Dockerfile.production
    container_name: test_booking_webapp
    expose:
      - 9002
    volumes:
      - .:/var/www/html
      - ./docker/config/webapp/php/ini/limitation.ini:/usr/local/etc/php/conf.d/limitation.ini
      - ./docker/config/webapp/php/ini/security.ini:/usr/local/etc/php/conf.d/security.ini
      - ./docker/config/webapp/php/ini/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./docker/config/webapp/php/ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    env_file: .env
    networks:
      - proxy

  nginx:
    image: nginx:stable-alpine
    container_name: test_booking_nginx
    networks:
      - proxy
    expose:
      - 80
      - 443
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./docker/data/nginx/logs:/var/log/nginx
      - ./:/var/www/html
      - ./docker/config/cert:/opt/cert
    depends_on:
      - webapp

networks:
  proxy:
    external:
      name: proxy
