<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
            body, p {
                font-family: 'Arial';
                font-weight: normal;
                font-size: 12px;
            }

            p {
                line-height: 12x;
            }

            b, strong {
                font-weight: bold;
            }

            .center {
                text-align: center;
            }

            .human-id {
                display: block;
                font-size: 18px;
                font-weight: bold;
                text-align: center;
                margin-bottom: 4px;
            }

            .policy-text {
                font-size: 10px;
                line-height: 10x;
                text-align: justify;
                padding-top: 0;
                padding-bottom: 0;
                padding-left: 0;
                padding-right: 0;
            }

            #qrCode {
                text-align: left;
                margin: 0;
                padding: 0;
            }

            #humanId {
                position: fixed;

                bottom: 0cm;
                left:   0cm;

                z-index:  -1000;
            }

            h1 {
                display: block;
                text-align: right;
                margin: 0;
            }

            .places {
                font-size: 16px;
                overflow-wrap: break-word;
            }

            .ow {
                overflow-wrap: break-word;
                word-wrap: break-word;
                hyphens: auto;
            }

            .page_break { page-break-before: always; }
        </style>
    </head>

    <body>
        <table style="width: 100%;border-collapse: collapse;line-height: 16px;margin-top: 0px;margin-bottom: 10px;">
            <tbody>
                <tr>
                    <td width="60" style="text-align: left;"><div class="human-id"><?=$humanID;?></div><img id="qrCode" width="80" height="80" src="<?=$qrCode;?>" /></td>
                    <td style="padding-left: 6px;"><div class="places"><b><?=$time;?></b><br><div class="ow"><?=$place;?></div></div></td>
                    <td width="240"><h1>ADATFELVÉTELI LAP</h1><p style="text-align: right;margin:0;padding:0;">SARS-CoV-2 antigén gyorsteszt önkéntes vizsgálathoz.</p></td>
                </tr>
            </tbody>
        </table>

        <div style="height: 12px"></div>

        <table style="width: 100%;border-collapse: collapse;line-height: 14px;">
            <tr>
                <td width="50">Név</td>
                <td style="font-size: 14px;"><b><?=$fullName;?></b></td>
                <td>Születési hely, dátum</td>
                <td style="font-size: 14px;"><b><?=$birthPlace;?>, <?=$birthday;?></b></td>
            </tr>
            <tr>
                <td width="50">TAJ-szám</td>
                <td style="font-size: 14px;"><b><?=$taj;?></b></td>
                <td>Telefonszám</td>
                <td style="font-size: 14px;"><b>+<?=$phone;?></b></td>
            </tr>
            <tr>
                <td width="50">E-mail</td>
                <td style="font-size: 14px;"><b><?=$email;?></b></td>
                <td></td>
                <td></td>
            </tr>
        </table>

        <table style="width: 100%;border-collapse: collapse;line-height: 14px;">
            <tr>
                <td width="50">Lakcím</td>
                <td style="font-size: 14px;"><b><?=$address;?></b></td>
            </tr>
        </table>

        <p style="text-align: justify;">A szűrővizsgálatra jelentkező személy jelen adatfelvételi lap aláírásával igazolja, hogy a vizsgálat elvégzéséhez <b>önként hozzájárult.</b></p>
        <p style="text-align: justify;">Tájékoztatjuk, hogy a gyorsteszt módszerrel történő tesztelésről és a vizsgálat eredményéről adatlap és eredményközlő lap kerül majd kitöltésre és átadásra.</p>
        <p style="text-align: justify;">A vizsgálatra jelentkező személy tudomásul veszi, hogy pozitív eredmény esetén haladéktalanul értesítenie kell háziorvosát, aki a Nemzeti Népegészségügyi Központ által kiadott eljárásrendben foglaltak szerint fog eljárni, és az 1/2014. EMMI Rendelet alapján az elvégzett teszt eredményét a vizsgált személy a tesztet elvégző szolgáltatónak a vizsgált személy személyazonosító adataival együtt jelentenie kell a központi járványügyi rendszer felé (OSZIR).</p>
        <p style="text-align: justify;"><b>A pozitív vizsgálati eredmény járványügyi intézkedést von maga után, ezért a vizsgálati eredmény</b> a fertőző betegségek jelentésének rendjéről szóló 1/2014. (I. 16.) EMMI rendelet alapján <b>a vizsgált személy személyazonosító adataival együtt rögzítésre kerül az országos egészségügyi adatgyűjtő és járványügyi rendszerekben</b> (OSZIR), melyről a járványügyi hatóságok is értesülnek.</p>

        <p><b>Aktuális egészségügyi állapot (a vizsgálat napján töltse ki):</b></p>
        <p>Tapasztalja-e a következő tüneteket? (megfelelő rész aláhúzandó)</p>

        <table style="width: 100%;border-collapse: collapse;">
            <tbody>
                <tr>
                    <td width="180">Láz</td>
                    <td>igen / nem</td>
                    <td width="180">Nehézlégzés, légszomj</td>
                    <td>igen / nem</td>
                </tr>
                <tr>
                    <td width="180">Száraz köhögés</td>
                    <td>igen / nem</td>
                    <td width="180">Íz és/vagy szaglásvesztés</td>
                    <td>igen / nem</td>
                </tr>
                <tr>
                    <td width="180">Torokfájdalom</td>
                    <td>igen / nem</td>
                    <td width="180">Gyengeség</td>
                    <td>igen / nem</td>
                </tr>
                <tr>
                    <td width="180">Hasmenés</td>
                    <td>igen / nem</td>
                    <td width="180">Izomfájdalom</td>
                    <td>igen / nem</td>
                </tr>
            </tbody>
        </table>

        <p style="text-align: justify;">Ha fentiek közül jelölt be valamit, mikor jelentkeztek a tünetek?</p>
        <p>..........................................................................................................</p>

        <p style="text-align: justify;">Az elmúlt 14 napban került-e szoros kapcsolatba (1,5 méteren belül, 15 percnél hosszabb ideig, maszk nélkül) ismert, vagy tudomása szerint később megbetegedett COVID-19 beteg személlyel?</p>
        <p>igen / nem</p>

        <b>Adatkezelés</b>
        <p class="policy-text">A vizsgálathoz kapcsolódó adatkezelés célja: a COVID-19 antigén gyorsteszt elvégzése és az ehhez kapcsolódó jogszabályi kötelezettségen alapuló minimális adatkezelés (vizsgálat elvégzésének, körülményeinek dokumentálása, a vizsgált személy és az eredményt kapó személy azonosítása, járványügyi hatóságok felé fennálló adattovábbítási kötelezettség teljesítése). A tesztet végző szolgáltató mint adatkezelő (<?=$infoCompanyFullInfo;?>) a rendelkezésre bocsátott adatokat célhoz kötötten, kizárólag az érintett egészségügyi ellátásához szükséges tevékenységekhez rögzíti, illetve továbbítja. Az adatoknak a szolgáltató rendelkezésére bocsátása nélkül a teszt elvégeztetésére nincs lehetőség.</p>

        <p class="policy-text">A vizsgálat elvégzéséhez szükséges adatok kezeléséről, az adatkezeléssel összefüggő jogai (tájékoztatáshoz, hozzáféréshez, törléshez, illetve tiltakozáshoz való jog, jogorvoslati jog) gyakorlásának módjáról bővebb tájékoztatást a tesztállomáson kihelyezett részletes adatkezelési tájékoztató tartalmazza, illetve kérdéseire szóban a szolgáltató tesztet végző munkatársaitól lehet tájékoztatást kérni.</p>

        <p style="text-align: justify;"><b>Fentieket megértettem és tudomásul vettem, a fenti adatok a valóságnak megfelelnek, adataimat önként adtam meg, konkrét, egyértelmű, megfelelő tájékoztatás után, amit aláírásommal igazolok.</b></p>

        <div style="height: 20px"></div>

        <table style="width: 100%;border: 0;border-collapse: collapse;">
            <tbody>
                <tr>
                    <td>Budapest, <?=$signDate;?></td>
                    <td style="text-align: right;">..............................................................</td>
                </tr>
                <tr>
                    <td></td>
                    <td><div style="text-align: right;margin-right: 80px;">Aláírás<div></td>
                </tr>
            </tbody>
        </table>

        <table id="humanId" style="width: 100%;border: 0;border-collapse: collapse;">
            <tbody>
                <tr>
                    <td><?=$humanID;?></td>
                    <td style="text-align: right;"><?=$humanID;?></td>
                </tr>
            </tbody>
        </table>

    </body>
</html>
