<p>Kedves <?=$name;?>!</p>

<p>A <?=$infoMunicipality;?> célja, hogy minél több budapesti lakost le tudjon tesztelni. Kérjük, hogy segítse munkánkat azzal, hogy ha előreláthatólag tudja, hogy nem fog tudni részt venni a gyorstesztelésen, akkor az alábbi linken lemondja. Ezzel felszabadul az Ön időpontja és lehetőséget add arra, hogy más tudjon regisztrálni.</p>

<p>Lemondáshoz <a href="<?=$infoUrl;?>/lemondas/<?=$cancelHash;?>" target="_blank" rel="noopener">kattintson ide</a>.</p>

<p>Köszönjük, hogy segíti a munkánkat!</p>

<p>
    Üdvözlettel,<br>
    <?=$infoMunicipality;?>
</p>
