<p>Kedves <?=$name;?>!</p>

<p>A <?=$infoMunicipality;?> célja, hogy minél inkább a budapestiek igényeihez igazítsa szolgáltatásait.</p>

<p>Ön regisztrált az önkormányzat karácsony előtti COVID-19 gyorstesztelésére.</p>

<p>Kérjük, hogy segítse munkánkat azzal, hogy visszajelez nekünk, milyen volt részt venni a tesztelésen. Akkor is várjuk visszajelzését, ha végül nem tudott részt venni.</p>

<p>Kattintson ide rövid kérdőívünk kitöltéséhez!<br />
<a href="<?=$url;?>" target="_blank" rel="noopener"><?=$url;?></a>
</p>

<p>Köszönjük, hogy segíti a munkánkat!</p>

<p>
    Üdvözlettel,<br>
    <?=$infoMunicipality;?>
</p>
